user_word = input("Enter a word: ")
print(f"You entered: {user_word}")  
print(f"The length of the word is: {len(user_word)}")
print(f"The word in uppercase is: {user_word.upper()}") 
print(f"The word in lowercase is: {user_word.lower()}")
print(f"The first character of the word is: {user_word[0]}")
print(f"The last character of the word is: {user_word[-1]}")    
print(f"The word repeated 3 times on the same line is: {(user_word +" ") * 3}")
print(f"The word repeated 3 times on separate lines is:\n{user_word}\n{user_word}\n{user_word}")
